import DarkModeProvider from "./components/Providers/DarkModeProvider"

import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import { AuthContextProvider } from "./context/AuthContext";

export const poppins = Roboto({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"]
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <DarkModeProvider>
        <AuthContextProvider>
          <body
            className={`${poppins.className} antialiased`}
          >
            <Header />
            {children}
          </body>
        </AuthContextProvider>
      </DarkModeProvider>
    </html>
  );
}
